import QRCode from "qrcode";
import { buildTrackingUrl, TRACKING_QR_OPTIONS } from "./tracking";

const brandLogo = "/manus-storage/servicom_logo_final_e7ce35aa.png";

const escapeHtml = (value: unknown) => String(value ?? "").replace(/&/g, "&amp;").replace(/</g, "&lt;").replace(/>/g, "&gt;").replace(/\"/g, "&quot;").replace(/'/g, "&#039;");
const fullName = (name?: string | null, lastName?: string | null) => `${name ?? ""} ${lastName ?? ""}`.trim() || "No especificado";

export function printUserShipmentReceipt(shipment: any): void {
  if (!shipment?.orderNumber || !shipment?.code) return;
  const printWindow = window.open("", "_blank", "width=900,height=900");
  if (!printWindow) { window.alert("Permite las ventanas emergentes para abrir el recibo."); return; }

  const trackingUrl = buildTrackingUrl(shipment.orderNumber, shipment.code);
  const order = escapeHtml(shipment.orderNumber);
  const code = escapeHtml(shipment.code);
  const sender = escapeHtml(fullName(shipment.senderName, shipment.senderLastName));
  const recipient = escapeHtml(fullName(shipment.recipientName, shipment.recipientLastName));
  const senderPhone = escapeHtml(shipment.senderPhone || "No especificado");
  const senderDni = escapeHtml(shipment.senderDni || "No especificado");
  const recipientPhone = escapeHtml(shipment.recipientPhone || "No especificado");
  const recipientDni = escapeHtml(shipment.recipientDni || "No especificado");
  const notes = escapeHtml(shipment.notes || "Documentación lícita");
  const createdAt = new Date(shipment.createdAt || Date.now()).toLocaleString("es-PE");
  const today = new Date().toLocaleDateString("es-PE", { day: "numeric", month: "long", year: "numeric" });
  const shortCode = escapeHtml(String(shipment.code).split("-").pop());

  printWindow.document.write(`<!doctype html><html lang="es"><head><meta charset="utf-8"><title>Recibo ${order} - Servicom Internacional</title><style>
@media print{.page-break{page-break-before:always}}*{box-sizing:border-box}body{font-family:Arial,Helvetica,sans-serif;margin:0;padding:30px;color:#0B2B5E;line-height:1.4}.header{display:flex;justify-content:space-between;gap:20px;align-items:flex-start;border-bottom:3px solid #F28C00;padding-bottom:14px}.logo{width:150px;height:82px;object-fit:contain;object-position:left center}.company{font-size:24px;font-weight:700;margin:5px 0 0}.subtitle{color:#F28C00;font-weight:700;font-size:13px}.contact{color:#555;font-size:10px;margin-top:6px}.seal{border:2px solid #0B2B5E;border-radius:8px;padding:10px;min-width:190px;font-size:10px}.seal-title{font-weight:700;text-align:center;border-bottom:1px solid #0B2B5E;padding-bottom:4px;margin-bottom:5px}.title{text-align:center;background:#f4f6f8;padding:10px;margin:20px 0;font-size:19px;font-weight:700}.section{margin:15px 0}.section-title{border-left:4px solid #F28C00;padding-left:8px;font-weight:700;text-transform:uppercase;margin-bottom:8px}.grid{display:grid;grid-template-columns:1fr 1fr;gap:6px 20px;font-size:12px}.line{border-bottom:1px dotted #aaa;min-height:20px}.label{font-weight:700;color:#444}.content{min-height:52px;border:1px solid #ddd;padding:8px;font-size:12px}.qr-wrap{display:flex;justify-content:space-around;align-items:center;gap:20px;background:#fafafa;border:1px solid #e5e7eb;padding:14px;margin-top:20px}.qr-box{text-align:center;font-size:10px;color:#555}#qr{width:150px;height:150px}.ticket{border:2px dashed #0B2B5E;margin-top:35px;padding:14px;position:relative}.ticket:before{content:"✂ RECORTAR Y ADJUNTAR AL FOLDER MANILA";position:absolute;top:-12px;left:16px;background:white;padding:0 7px;color:#0B2B5E;font-size:10px;font-weight:700}.ticket-title{text-align:center;font-weight:700;margin-bottom:10px}.ticket-grid{display:grid;grid-template-columns:1fr auto;gap:10px;align-items:center;font-size:11px}.ticket-code{border:2px solid #0B2B5E;padding:7px;font-size:20px;font-weight:700}.declaration-title{text-align:center;margin:10px 0 28px}.declaration{font-size:12px;text-align:justify;line-height:1.6}.signature-area{display:flex;justify-content:space-between;gap:45px;margin-top:65px}.signature{flex:1;border-top:1px dashed #000;text-align:center;padding-top:8px;font-size:11px}.fingerprint{width:95px;height:115px;border:1px solid #000;margin:0 auto 8px}.footer{text-align:center;font-size:9px;color:#888;margin-top:35px}</style></head><body>
<section><div class="header"><div><img class="logo" src="${brandLogo}" alt="Servicom Internacional"><div class="company">SERVICOM INTERNACIONAL</div><div class="subtitle">en colaboración con Kasega Tour EIRL</div><div class="contact">RUC: 20615004708 · peruservicom@gmail.com · +51 970 188 447 / +51 908 722 617 · 01 390 7269</div></div><div class="seal"><div class="seal-title">RECIBO DE ENVÍO</div><strong>Orden:</strong> ${order}<br><strong>Cód. envío:</strong> ${code}<br><strong>Fecha:</strong> ${createdAt}</div></div>
<div class="title">INFORMACIÓN DE ENVÍO DE DOCUMENTO</div><div class="section"><div class="section-title">Remitente</div><div class="grid"><div><span class="label">Nombre:</span> <span class="line">${sender}</span></div><div><span class="label">DNI/RUC:</span> <span class="line">${senderDni}</span></div><div><span class="label">Celular:</span> <span class="line">${senderPhone}</span></div></div></div><div class="section"><div class="section-title">Destinatario</div><div class="grid"><div><span class="label">Nombre:</span> <span class="line">${recipient}</span></div><div><span class="label">DNI/C.I.:</span> <span class="line">${recipientDni}</span></div><div><span class="label">Celular:</span> <span class="line">${recipientPhone}</span></div></div></div><div class="section"><div class="section-title">Descripción y tarifa</div><div class="content">${notes}</div></div><div class="qr-wrap"><div class="qr-box"><canvas id="qr"></canvas><div>Escanea para rastrear el envío</div></div><div style="font-size:11px;max-width:310px"><strong>Tarifa documental:</strong> 50 € por documentos apostillados, traducidos o legalizados. Se agregan 10 € por cada documento adicional de la misma naturaleza.<br><br><strong>Estado inicial:</strong> ${escapeHtml(shipment.status || "En agencia")}</div></div><div class="ticket"><div class="ticket-title">CONTROL DE ENTREGA — TORINO, ITALIA</div><div class="ticket-grid"><div><strong>ORDEN:</strong> ${order}<br><strong>DESTINO:</strong> TORINO, ITALIA<br><strong>RECEPTOR:</strong> ${recipient}</div><div class="ticket-code">${shortCode}</div></div></div></section>
<section class="page-break"><div class="header"><div><img class="logo" src="${brandLogo}" alt="Servicom Internacional"><div class="company">SERVICOM INTERNACIONAL</div><div class="subtitle">en colaboración con Kasega Tour EIRL</div></div><div class="seal">RUC: 20615004708<br>Orden: ${order}</div></div><div class="declaration-title"><h2>DECLARACIÓN JURADA DE CONTENIDO</h2><h3>Y EXENCIÓN DE RESPONSABILIDAD LEGAL</h3></div><div class="declaration"><p>Yo, <strong>${sender}</strong>, identificado(a) con documento de identidad N° <strong>${senderDni}</strong>, declaro bajo juramento que el envío amparado bajo la Orden N° <strong>${order}</strong> contiene <strong>ÚNICA Y ESTRICTAMENTE DOCUMENTACIÓN LÍCITA</strong>.</p><p>Garantizo que los documentos entregados no ocultan ni camuflan sustancias estupefacientes, alcaloides, dinero no declarado u otro material prohibido por la legislación peruana y los convenios aduaneros vigentes.</p><p>Mediante mi firma y huella dactilar asumo la responsabilidad penal, civil y administrativa ante las autoridades competentes si se detectan alteraciones, camuflajes o sustancias ilícitas en mi envío.</p><p>Eximo de responsabilidad operativa o financiera a <strong>Servicom Internacional</strong> y a su socio estratégico Kasega Tour E.I.R.L. (RUC: 20615004708), y autorizo la apertura, revisión física y escaneo del envío por la agencia o las autoridades competentes.</p><p>Suscrito en la ciudad de Lima, el ${today}.</p></div><div class="signature-area"><div class="signature"><div style="height:90px"></div><strong>Firma del Remitente</strong><br>DNI/Pasaporte N° ${senderDni}</div><div style="width:30%;text-align:center;font-size:11px"><div class="fingerprint"></div><strong>Huella Dactilar</strong><br>(Índice Derecho)</div></div><div class="footer">Anexo de trabajo para revisión y firma del remitente. La empresa debe validar el contenido legal con un profesional antes de usarlo como documento formal.</div></section></body></html>`);
  printWindow.document.close();
  setTimeout(() => { const canvas = printWindow.document.getElementById("qr") as HTMLCanvasElement | null; if (canvas) QRCode.toCanvas(canvas, trackingUrl, { ...TRACKING_QR_OPTIONS, width: 150, margin: 1, color: { dark: "#0B2B5E", light: "#ffffff" } }); printWindow.focus(); printWindow.print(); }, 500);
}
