CREATE TABLE `recipient_change_requests` (
	`id` int AUTO_INCREMENT NOT NULL,
	`shipmentId` int NOT NULL,
	`accountId` int,
	`requestedByAdminId` int NOT NULL,
	`requestedByLabel` varchar(255) NOT NULL,
	`requestTokenHash` varchar(128) NOT NULL,
	`requestTokenExpiresAt` timestamp NOT NULL,
	`status` enum('pending','signed','cancelled','expired') NOT NULL DEFAULT 'pending',
	`senderName` varchar(255) NOT NULL,
	`senderLastName` varchar(255),
	`senderDni` varchar(20),
	`senderDocumentType` enum('dni_peru','pasaporte','carta_identita_italia') NOT NULL DEFAULT 'dni_peru',
	`previousRecipientName` varchar(255),
	`previousRecipientLastName` varchar(255),
	`previousRecipientDni` varchar(20),
	`previousRecipientDocumentType` enum('dni_peru','pasaporte','carta_identita_italia') NOT NULL DEFAULT 'dni_peru',
	`previousRecipientPhone` varchar(32),
	`newRecipientName` varchar(255) NOT NULL,
	`newRecipientLastName` varchar(255) NOT NULL,
	`newRecipientDni` varchar(20) NOT NULL,
	`newRecipientDocumentType` enum('dni_peru','pasaporte','carta_identita_italia') NOT NULL DEFAULT 'dni_peru',
	`newRecipientPhone` varchar(32) NOT NULL,
	`route` varchar(100) NOT NULL,
	`declarationVersion` varchar(64) NOT NULL DEFAULT 'recipient-change-v1',
	`notificationSentAt` timestamp,
	`emailSentAt` timestamp,
	`signerName` varchar(255),
	`signerEmail` varchar(320),
	`signerAccountId` int,
	`consentTextVersion` varchar(64),
	`consentAcceptedAt` timestamp,
	`evidenceHash` varchar(128),
	`signatureStrokes` longtext,
	`signedAt` timestamp,
	`appliedAt` timestamp,
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	`updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `recipient_change_requests_id` PRIMARY KEY(`id`),
	CONSTRAINT `recipient_change_requests_requestTokenHash_unique` UNIQUE(`requestTokenHash`)
);
--> statement-breakpoint
CREATE INDEX `recipient_change_requests_shipment_idx` ON `recipient_change_requests` (`shipmentId`,`createdAt`);--> statement-breakpoint
CREATE INDEX `recipient_change_requests_account_idx` ON `recipient_change_requests` (`accountId`,`createdAt`);--> statement-breakpoint
CREATE INDEX `recipient_change_requests_status_idx` ON `recipient_change_requests` (`status`,`requestTokenExpiresAt`);